### ISSUE TITLE
meinkraft is dead

### ISSUE THREAD

**Issue by ThatLing** [glua-team/glua-team.github.io#65]
glua.team minecraft server is dead (rip btw)
christmas is also over

**Comment by meepen** [comment]
@SwadicalRag @SwadicalRag @SwadicalRag

**Comment by SwadicalRag** [comment]
REJOICE IT'S ALMOST CHRISTMAS

**Comment by ThatLing** [comment]
its summer in australia

**Comment by meepen** [comment]
Truu


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Ling <notifications@github.com> Date: 9/24/17  10:44 AM  (GMT-05:00) To: "glua-team/glua-team.github.io" <glua-team.github.io@noreply.github.com> Cc: Meepen <meepdarknessmeep@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [glua-team/glua-team.github.io] meinkraft is dead (#65) 
its summer in australia

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/glua-team/glua-team.github.io","title":"glua-team/glua-team.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/glua-team/glua-team.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ThatLing in #65: its summer in australia"}],"action":{"name":"View Issue","url":"https://github.com/glua-team/glua-team.github.io/issues/65#issuecomment-331714590"}}}

**Comment by SwadicalRag** [comment]
i said it was CHRISTMAS not WINTER genius

Sent from my B-Mobile 9G UTE Device

**Comment by meepen** [comment]
thanks samsung

**Comment by Jvs34** [comment]
yes


sEnT fRoM My CoMpUtEr

**Comment by ThatLing** [comment]
christmas is dead again

**Comment by BeastMichael** [comment]
rest in pieces glooa.team
